#!/usr/bin/env python3

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "ls_cx_ss"
OUTPUTS = [ROOT / "docs" / "ls-cx-ss.py"]
MODULE_ORDER = [
    "ls_cx_ss",
    "ls_cx_ss.model",
    "ls_cx_ss.timefmt",
    "ls_cx_ss.query",
    "ls_cx_ss.render",
    "ls_cx_ss.scanner",
    "ls_cx_ss.distribution",
    "ls_cx_ss.tui",
    "ls_cx_ss.cli",
]
MODULE_FILES = {
    "ls_cx_ss": PACKAGE_DIR / "__init__.py",
    "ls_cx_ss.model": PACKAGE_DIR / "model.py",
    "ls_cx_ss.timefmt": PACKAGE_DIR / "timefmt.py",
    "ls_cx_ss.query": PACKAGE_DIR / "query.py",
    "ls_cx_ss.render": PACKAGE_DIR / "render.py",
    "ls_cx_ss.scanner": PACKAGE_DIR / "scanner.py",
    "ls_cx_ss.distribution": PACKAGE_DIR / "distribution.py",
    "ls_cx_ss.tui": PACKAGE_DIR / "tui.py",
    "ls_cx_ss.cli": PACKAGE_DIR / "cli.py",
}


def module_sources():
    return {name: path.read_text(encoding="utf-8") for name, path in MODULE_FILES.items()}


def render_single_file() -> str:
    sources = json.dumps(module_sources(), ensure_ascii=False, indent=2, sort_keys=False)
    module_order = json.dumps(MODULE_ORDER, ensure_ascii=False, indent=2)
    return """#!/usr/bin/env python3
# Generated by scripts/build_single_file.py. Do not edit directly.

import sys
import types

MODULE_SOURCES = {sources}
MODULE_ORDER = {module_order}


def _load_module(name):
    module = types.ModuleType(name)
    module.__file__ = "<generated {{0}}>".format(name)
    module.__package__ = "ls_cx_ss"
    if name == "ls_cx_ss":
        module.__path__ = []
    sys.modules[name] = module
    exec(compile(MODULE_SOURCES[name], module.__file__, "exec"), module.__dict__)
    return module


def _bootstrap():
    for name in MODULE_ORDER:
        if name not in sys.modules:
            _load_module(name)
    return sys.modules["ls_cx_ss.cli"]


if __name__ == "__main__":
    raise SystemExit(_bootstrap().main())
""".format(sources=sources, module_order=module_order)


def main() -> int:
    rendered = render_single_file()
    for output in OUTPUTS:
        output.write_text(rendered, encoding="utf-8")
        output.chmod(0o755)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
